#!/bin/bash
###################################################
# Package script for TnRP which generates an RPM. #
###################################################

# exit on errors
set -e

# required argument; defines the version number for the artifact
VERSION="1.0"

# required argument; rpm should be unique, generate a timestamp
ITERATION=$(date +"%Y%m%d%H%M%S")

echo "----- Start CPT Tools TnRP package script -----"
echo "pwd: $(pwd)"
echo "version: $VERSION"
echo "iteration: $ITERATION"

# current directory is /opt/pipeline/scripts/<pipeline_name> where the package script will reside in the build host
cd $(dirname ${0})
pushd ..
echo "pwd2: $(pwd)"
echo "lsl: $(ls -l)"

# build the package by running the build script in repo root dir
./build.sh -i $ITERATION -v $VERSION

# copy the rpm generated to $TNRP_BUILD_ARTIFACTS (TnRP specified env variable) to be used by the next pipeline segment
cp *.rpm $TNRP_BUILD_ARTIFACTS